"use client";

import { useMemo } from "react";
import Link from "next/link";
import { ChevronLeft, Printer } from "lucide-react";
import { useStore } from "@/lib/store";
import { formatFriendly, dayKey, lastNDays } from "@/lib/dates";
import { Card, PageHeader } from "@/components/ui/Card";
import { skinTrends, skinLifestyleConnections } from "@/lib/skinInsights";

export default function SkinReportPage() {
  const skinCheckIns = useStore((s) => s.skinCheckIns);
  const checkIns = useStore((s) => s.checkIns);
  const products = useStore((s) => s.skinProducts);
  const experiments = useStore((s) => s.skinExperiments);
  const photos = useStore((s) => s.skinPhotos);
  const settings = useStore((s) => s.settings);

  const trends = useMemo(() => skinTrends(skinCheckIns), [skinCheckIns]);
  const connections = useMemo(() => skinLifestyleConnections(skinCheckIns, checkIns), [skinCheckIns, checkIns]);

  const concernCounts = useMemo(() => {
    const counts = new Map<string, number>();
    skinCheckIns.forEach((c) => c.areas.forEach((a) => counts.set(a, (counts.get(a) ?? 0) + 1)));
    return [...counts.entries()].sort((a, b) => b[1] - a[1]);
  }, [skinCheckIns]);

  const last90 = skinCheckIns.filter((c) => lastNDays(90).includes(c.date));

  return (
    <div className="mx-auto max-w-2xl pb-10">
      <div className="mb-4 flex items-center justify-between print:hidden">
        <Link href="/skin" className="flex items-center gap-1 text-sm text-ink-soft"><ChevronLeft size={16} /> Skin</Link>
        <button onClick={() => window.print()} className="flex items-center gap-1.5 rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-ink">
          <Printer size={15} /> Print / Save PDF
        </button>
      </div>

      <PageHeader
        eyebrow="Skin tracking summary"
        title={`${settings.displayName ? `${settings.displayName}'s` : "My"} skin report`}
        subtitle={`Generated ${formatFriendly(dayKey())}`}
      />

      <Card className="mb-4 border-primary/20 bg-primary-soft">
        <p className="text-sm text-ink">
          This report contains <strong>user-recorded observations only</strong> — not an AI or medical diagnosis. It's meant to give a
          dermatologist or other provider context on patterns you've noticed; it doesn't replace an in-person exam.
        </p>
      </Card>

      <Section title="Tracking overview">
        <p className="text-sm text-ink-soft">{skinCheckIns.length} skin check-ins recorded, {last90.length} in the last 90 days.</p>
        <p className="text-sm text-ink-soft">{photos.length} progress photos on file (front / left / right).</p>
      </Section>

      <Section title="Recent trends (30 days)">
        <ul className="space-y-1.5 text-sm text-ink-soft">
          {trends.map((t) => (
            <li key={t.field}>• {t.text}</li>
          ))}
        </ul>
      </Section>

      {concernCounts.length > 0 && (
        <Section title="Most frequently recorded areas of concern">
          <ul className="space-y-1 text-sm text-ink-soft">
            {concernCounts.map(([area, count]) => (
              <li key={area}>• {area} — logged {count} time{count === 1 ? "" : "s"}</li>
            ))}
          </ul>
        </Section>
      )}

      <Section title="Routine history">
        {products.length === 0 ? (
          <p className="text-sm text-ink-faint">No products logged.</p>
        ) : (
          <ul className="space-y-1.5 text-sm text-ink-soft">
            {products.map((p) => (
              <li key={p.id}>
                • {p.name} ({p.category}, {p.routine}) — started {formatFriendly(new Date(p.startedAt).toISOString().slice(0, 10))}
                {p.stoppedAt ? `, stopped ${formatFriendly(new Date(p.stoppedAt).toISOString().slice(0, 10))}` : ""}
              </li>
            ))}
          </ul>
        )}
      </Section>

      <Section title="Product changes / experiments">
        {experiments.length === 0 ? (
          <p className="text-sm text-ink-faint">None logged.</p>
        ) : (
          <ul className="space-y-1.5 text-sm text-ink-soft">
            {experiments.map((e) => (
              <li key={e.id}>• {e.productName} — {e.changeType} {formatFriendly(e.startDate)}{e.notes ? `: ${e.notes}` : ""}</li>
            ))}
          </ul>
        )}
      </Section>

      {connections.length > 0 && (
        <Section title="Relevant lifestyle patterns (from this user's own data)">
          <ul className="space-y-1.5 text-sm text-ink-soft">
            {connections.map((c) => (
              <li key={c.id}>• {c.text}</li>
            ))}
          </ul>
        </Section>
      )}

      <p className="mt-6 text-center text-xs text-ink-faint print:mt-10">
        Generated by Bloom from on-device, self-reported tracking data. Not a substitute for professional evaluation.
      </p>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Card className="mb-4 break-inside-avoid">
      <p className="mb-2 text-sm font-semibold text-ink">{title}</p>
      {children}
    </Card>
  );
}
