// Real, well-known songs. We publish only the chord progression — a
// functional, non-copyrightable building block (the same reason every chord
// -chart site can publish these) — plus capo/tempo/structure. No lyrics, no
// note-for-note transcription of the recording.
export interface PopularSongSection {
  name: string;
  chords: string[];
  strumPattern: string;
}

export interface PopularSong {
  title: string;
  artist: string;
  capo: number;
  difficulty: 1 | 2 | 3 | 4 | 5;
  bpm: number;
  timeSignature: string;
  chordsUsed: string[];
  sections: PopularSongSection[];
  tip: string;
}

export const POPULAR_SONGS: PopularSong[] = [
  {
    title: "Wonderwall",
    artist: "Oasis",
    capo: 2,
    difficulty: 2,
    bpm: 87,
    timeSignature: "4/4",
    chordsUsed: ["Em7", "G", "Cadd9", "D"],
    sections: [
      { name: "Verse", chords: ["Em7", "G", "Dsus4", "A7sus4"], strumPattern: "D DU D DU" },
      { name: "Chorus", chords: ["Cadd9", "D", "Em7", "G"], strumPattern: "D D DU D" },
      { name: "Bridge", chords: ["C", "D", "Em", "G"], strumPattern: "D DU D DU" },
    ],
    tip: "The whole song lives on four chord shapes with a capo on fret 2 — the hardest part is the fast Em7→G change.",
  },
  {
    title: "Perfect",
    artist: "Ed Sheeran",
    capo: 1,
    difficulty: 2,
    bpm: 63,
    timeSignature: "4/4",
    chordsUsed: ["G", "Em", "C", "D"],
    sections: [
      { name: "Verse", chords: ["G", "Em", "C", "D"], strumPattern: "D . DU . D ." },
      { name: "Chorus", chords: ["G", "Em", "C", "D"], strumPattern: "D DU UDU" },
    ],
    tip: "Same four chords the whole way through — capo 1 keeps it in the original key. Swap in Em7/Cadd9/Dsus4 later for color.",
  },
  {
    title: "Riptide",
    artist: "Vance Joy",
    capo: 1,
    difficulty: 2,
    bpm: 100,
    timeSignature: "4/4",
    chordsUsed: ["Am", "G", "C", "F"],
    sections: [
      { name: "Verse", chords: ["Am", "G", "C"], strumPattern: "D DU UDU" },
      { name: "Chorus", chords: ["Am", "G", "C", "F"], strumPattern: "D DU UDU" },
    ],
    tip: "Started life on ukulele, so the strum wants to feel light and bouncy rather than heavy.",
  },
  {
    title: "I'm Yours",
    artist: "Jason Mraz",
    capo: 4,
    difficulty: 2,
    bpm: 76,
    timeSignature: "4/4",
    chordsUsed: ["G", "D", "Em", "C"],
    sections: [
      { name: "Verse", chords: ["G", "D", "Em", "C"], strumPattern: "D DU UDU" },
      { name: "Chorus", chords: ["G", "D", "Em", "C"], strumPattern: "D DU UDU" },
    ],
    tip: "One loop, all the way through — great song for building strumming stamina.",
  },
  {
    title: "Thinking Out Loud",
    artist: "Ed Sheeran",
    capo: 2,
    difficulty: 3,
    bpm: 79,
    timeSignature: "4/4",
    chordsUsed: ["D", "G", "A", "Bm"],
    sections: [
      { name: "Verse", chords: ["D", "G", "A"], strumPattern: "D DU D DU" },
      { name: "Chorus", chords: ["D", "G", "A", "Bm"], strumPattern: "D DU D DU" },
    ],
    tip: "The chorus adds Bm into the mix — a great first mini-barre chord to learn.",
  },
  {
    title: "Hey, Soul Sister",
    artist: "Train",
    capo: 4,
    difficulty: 2,
    bpm: 97,
    timeSignature: "4/4",
    chordsUsed: ["C", "G", "Am", "F"],
    sections: [
      { name: "Verse", chords: ["C", "G", "Am", "F"], strumPattern: "D DU UDU" },
      { name: "Chorus", chords: ["C", "G", "Am", "F"], strumPattern: "D D UDU" },
    ],
    tip: "Capo 4 gets you that ukulele-bright tone from the original recording.",
  },
  {
    title: "Someone Like You",
    artist: "Adele",
    capo: 2,
    difficulty: 2,
    bpm: 67,
    timeSignature: "4/4",
    chordsUsed: ["G", "D", "Em", "C"],
    sections: [
      { name: "Verse", chords: ["G", "D", "Em", "C"], strumPattern: "D . . D . U ." },
      { name: "Chorus", chords: ["G", "D", "Em", "C"], strumPattern: "D DU UDU" },
    ],
    tip: "Written on piano, so let the chords ring out — this one rewards a soft touch over a hard strum.",
  },
  {
    title: "Free Fallin'",
    artist: "Tom Petty",
    capo: 3,
    difficulty: 1,
    bpm: 95,
    timeSignature: "4/4",
    chordsUsed: ["D", "G", "A"],
    sections: [
      { name: "Verse", chords: ["D", "G", "D", "A"], strumPattern: "D DU UDU" },
      { name: "Chorus", chords: ["D", "G", "D", "A"], strumPattern: "D DU UDU" },
    ],
    tip: "Only three chords — one of the best songs for a brand new player's first full song.",
  },
  {
    title: "Let It Be",
    artist: "The Beatles",
    capo: 0,
    difficulty: 2,
    bpm: 73,
    timeSignature: "4/4",
    chordsUsed: ["C", "G", "Am", "F"],
    sections: [
      { name: "Verse", chords: ["C", "G", "Am", "F", "C", "G", "F", "C"], strumPattern: "D D DU D" },
      { name: "Chorus", chords: ["Am", "G", "F", "C"], strumPattern: "D DU D DU" },
    ],
    tip: "One of the most-covered progressions in pop — nail this and you can fake your way through hundreds of songs.",
  },
  {
    title: "Stand By Me",
    artist: "Ben E. King",
    capo: 0,
    difficulty: 1,
    bpm: 118,
    timeSignature: "4/4",
    chordsUsed: ["G", "Em", "C", "D"],
    sections: [
      { name: "Verse", chords: ["G", "Em", "C", "D"], strumPattern: "D . D . D ." },
      { name: "Chorus", chords: ["G", "Em", "C", "D"], strumPattern: "D . D . D ." },
    ],
    tip: "The textbook I–vi–IV–V progression — once this is under your fingers you'll hear it everywhere.",
  },
  {
    title: "Knockin' on Heaven's Door",
    artist: "Bob Dylan",
    capo: 0,
    difficulty: 1,
    bpm: 72,
    timeSignature: "4/4",
    chordsUsed: ["G", "D", "Am"],
    sections: [{ name: "Verse", chords: ["G", "D", "Am", "G", "D", "C"], strumPattern: "D D DU D" }],
    tip: "Two four-bar phrases, G-D-Am-Am then G-D-C-C — one of the first songs most people learn to sing along to.",
  },
  {
    title: "Sweet Home Alabama",
    artist: "Lynyrd Skynyrd",
    capo: 0,
    difficulty: 1,
    bpm: 98,
    timeSignature: "4/4",
    chordsUsed: ["D", "C", "G"],
    sections: [{ name: "Main riff", chords: ["D", "C", "G"], strumPattern: "D D D D" }],
    tip: "Just three chords on a loop — a great song for practicing clean, confident down-strums.",
  },
  {
    title: "Ring of Fire",
    artist: "Johnny Cash",
    capo: 0,
    difficulty: 1,
    bpm: 148,
    timeSignature: "4/4",
    chordsUsed: ["G", "C", "D"],
    sections: [{ name: "Verse", chords: ["G", "C", "G", "D"], strumPattern: "D DU D DU" }],
    tip: "Fast and bouncy — focus on keeping the strum light so it doesn't get ahead of you.",
  },
  {
    title: "Blowin' in the Wind",
    artist: "Bob Dylan",
    capo: 0,
    difficulty: 1,
    bpm: 104,
    timeSignature: "4/4",
    chordsUsed: ["G", "C", "D", "Am"],
    sections: [{ name: "Verse", chords: ["G", "C", "G", "D", "Am", "G", "D", "G"], strumPattern: "D D DU D" }],
    tip: "A folk classic that leans entirely on G, C, and D — perfect for a first campfire song.",
  },
  {
    title: "Brown Eyed Girl",
    artist: "Van Morrison",
    capo: 0,
    difficulty: 2,
    bpm: 148,
    timeSignature: "4/4",
    chordsUsed: ["G", "C", "D", "Em"],
    sections: [{ name: "Verse", chords: ["G", "C", "G", "D"], strumPattern: "D DU UDU" }],
    tip: "Quick chord changes at a bright tempo — a great test of how fast you can switch cleanly.",
  },
  {
    title: "Three Little Birds",
    artist: "Bob Marley",
    capo: 0,
    difficulty: 1,
    bpm: 137,
    timeSignature: "4/4",
    chordsUsed: ["A", "D", "E"],
    sections: [{ name: "Verse", chords: ["A", "D", "A", "E"], strumPattern: ". U . U . U . U" }],
    tip: "Play the upstrokes short and choppy for that reggae skank feel — accent beats 2 and 4.",
  },
  {
    title: "No Woman No Cry",
    artist: "Bob Marley",
    capo: 0,
    difficulty: 2,
    bpm: 78,
    timeSignature: "4/4",
    chordsUsed: ["C", "G", "Am", "F"],
    sections: [{ name: "Verse", chords: ["C", "G", "Am", "F", "C", "F", "G"], strumPattern: "D DU D DU" }],
    tip: "Let the chords ring long — this one is about feel, not speed.",
  },
  {
    title: "Wagon Wheel",
    artist: "Old Crow Medicine Show",
    capo: 2,
    difficulty: 2,
    bpm: 105,
    timeSignature: "4/4",
    chordsUsed: ["G", "D", "Em", "C"],
    sections: [{ name: "Verse/Chorus", chords: ["G", "D", "Em", "C"], strumPattern: "D DU UDU" }],
    tip: "One loop for the whole song — great for building stamina at a train-beat tempo.",
  },
  {
    title: "Ho Hey",
    artist: "The Lumineers",
    capo: 0,
    difficulty: 1,
    bpm: 75,
    timeSignature: "4/4",
    chordsUsed: ["C", "Am", "F", "G"],
    sections: [{ name: "Verse/Chorus", chords: ["C", "Am", "F"], strumPattern: "D D D D" }],
    tip: "Mostly hand-claps and stomps in the original — try muting your strings for the claps between chords.",
  },
  {
    title: "Better Together",
    artist: "Jack Johnson",
    capo: 0,
    difficulty: 2,
    bpm: 144,
    timeSignature: "4/4",
    chordsUsed: ["G", "D", "Em", "C"],
    sections: [{ name: "Verse", chords: ["G", "D", "Em", "C"], strumPattern: "D DU UDU" }],
    tip: "Keep it light and bouncy — a great one for a relaxed fingerstyle-meets-strum feel.",
  },
  {
    title: "Zombie",
    artist: "The Cranberries",
    capo: 0,
    difficulty: 2,
    bpm: 86,
    timeSignature: "4/4",
    chordsUsed: ["Em", "C", "G", "D"],
    sections: [{ name: "Verse/Chorus", chords: ["Em", "C", "G", "D"], strumPattern: "D D DU D" }],
    tip: "Dig in harder on the chorus — this one rewards dynamic contrast between verse and chorus.",
  },
  {
    title: "Wonderful Tonight",
    artist: "Eric Clapton",
    capo: 0,
    difficulty: 2,
    bpm: 78,
    timeSignature: "4/4",
    chordsUsed: ["G", "Em", "C", "D"],
    sections: [{ name: "Verse", chords: ["G", "Em", "C", "D"], strumPattern: "D . DU . D ." }],
    tip: "A slow ballad — let each chord breathe rather than rushing to the next one.",
  },
  {
    title: "I Will Follow You into the Dark",
    artist: "Death Cab for Cutie",
    capo: 0,
    difficulty: 2,
    bpm: 68,
    timeSignature: "4/4",
    chordsUsed: ["Am", "Fmaj7", "C", "G"],
    sections: [{ name: "Verse", chords: ["Am", "Fmaj7", "C", "G"], strumPattern: "D . . . D . . ." }],
    tip: "Fingerpicked in the original — try plucking the bass note then the rest of the chord for each one.",
  },
  {
    title: "Horse with No Name",
    artist: "America",
    capo: 0,
    difficulty: 1,
    bpm: 122,
    timeSignature: "4/4",
    chordsUsed: ["Em", "D6add9"],
    sections: [{ name: "Verse", chords: ["Em", "D6add9"], strumPattern: "D DU D DU" }],
    tip: "The entire song alternates just two chords — great practice for a clean, steady switch.",
  },
  {
    title: "Margaritaville",
    artist: "Jimmy Buffett",
    capo: 0,
    difficulty: 1,
    bpm: 148,
    timeSignature: "4/4",
    chordsUsed: ["D", "G", "A"],
    sections: [{ name: "Verse", chords: ["D", "G", "D", "A"], strumPattern: "D DU UDU" }],
    tip: "Classic I-IV-V in D — a fun, breezy strummer once G and D changes feel natural.",
  },
  {
    title: "Redemption Song",
    artist: "Bob Marley",
    capo: 0,
    difficulty: 2,
    bpm: 74,
    timeSignature: "4/4",
    chordsUsed: ["G", "Em", "C", "D"],
    sections: [{ name: "Verse", chords: ["G", "Em", "C", "D", "G", "C", "D"], strumPattern: "D DU D DU" }],
    tip: "Written for a single acoustic guitar — this one carries entirely on your dynamics and phrasing.",
  },
  {
    title: "Lean on Me",
    artist: "Bill Withers",
    capo: 0,
    difficulty: 2,
    bpm: 78,
    timeSignature: "4/4",
    chordsUsed: ["C", "F", "G", "Am"],
    sections: [{ name: "Verse", chords: ["C", "F", "C", "F", "C", "G", "Am", "F"], strumPattern: "D D DU D" }],
    tip: "A soul classic built on simple, strong chord movement — focus on hitting each change right on the beat.",
  },
  {
    title: "With or Without You",
    artist: "U2",
    capo: 0,
    difficulty: 2,
    bpm: 110,
    timeSignature: "4/4",
    chordsUsed: ["D", "A", "Bm", "G"],
    sections: [{ name: "Verse/Chorus", chords: ["D", "A", "Bm", "G"], strumPattern: "D . D . DU . D ." }],
    tip: "One four-chord loop for the entire song — this is where a clean Bm really pays off.",
  },
  {
    title: "Good Riddance (Time of Your Life)",
    artist: "Green Day",
    capo: 0,
    difficulty: 3,
    bpm: 96,
    timeSignature: "4/4",
    chordsUsed: ["G", "Cadd9", "D", "Em7", "Am7", "C"],
    sections: [{ name: "Verse", chords: ["G", "Cadd9", "D", "Em7", "C", "G", "D"], strumPattern: "D . DU . D ." }],
    tip: "Mostly fingerpicked in the original — try picking the bass note then the top strings for each chord.",
  },
  {
    title: "What a Wonderful World",
    artist: "Louis Armstrong",
    capo: 0,
    difficulty: 2,
    bpm: 44,
    timeSignature: "4/4",
    chordsUsed: ["G", "Em7", "Am7", "D7"],
    sections: [{ name: "Verse", chords: ["G", "Em7", "Am7", "D7"], strumPattern: "D . . . D . . ." }],
    tip: "Very slow and spacious — let every chord ring for the full bar.",
  },
  {
    title: "Twist and Shout",
    artist: "The Beatles",
    capo: 0,
    difficulty: 1,
    bpm: 124,
    timeSignature: "4/4",
    chordsUsed: ["D", "G", "A"],
    sections: [{ name: "Verse", chords: ["D", "G", "A"], strumPattern: "D DU D DU" }],
    tip: "Three chords, high energy — great for practicing fast, confident changes.",
  },
  {
    title: "Peaceful Easy Feeling",
    artist: "Eagles",
    capo: 0,
    difficulty: 2,
    bpm: 116,
    timeSignature: "4/4",
    chordsUsed: ["G", "D", "C"],
    sections: [{ name: "Verse", chords: ["G", "D", "C", "G"], strumPattern: "D DU UDU" }],
    tip: "Laid-back country-rock feel — keep the strum relaxed rather than driving.",
  },
  {
    title: "Sweet Caroline",
    artist: "Neil Diamond",
    capo: 0,
    difficulty: 2,
    bpm: 128,
    timeSignature: "4/4",
    chordsUsed: ["G", "C", "D", "Em"],
    sections: [{ name: "Verse", chords: ["G", "C", "D", "Em", "C", "D"], strumPattern: "D D DU D" }],
    tip: "Everyone knows the horn stabs before the chorus — try muting and popping the strings there.",
  },
  {
    title: "Iris",
    artist: "Goo Goo Dolls",
    capo: 0,
    difficulty: 2,
    bpm: 90,
    timeSignature: "4/4",
    chordsUsed: ["C", "G", "Am", "F"],
    sections: [{ name: "Verse/Chorus", chords: ["C", "G", "Am", "F"], strumPattern: "D DU D DU" }],
    tip: "A steady I-V-vi-IV loop — one of the most useful progressions in pop-rock to have under your fingers.",
  },
  {
    title: "Every Breath You Take",
    artist: "The Police",
    capo: 0,
    difficulty: 3,
    bpm: 117,
    timeSignature: "4/4",
    chordsUsed: ["Aadd9", "E", "F#m", "D"],
    sections: [{ name: "Verse", chords: ["Aadd9", "E", "F#m", "D"], strumPattern: "D DU D DU" }],
    tip: "F#m is the challenge here — it's the same barre shape as F#m in the Chords learning path.",
  },
  {
    title: "Under the Bridge",
    artist: "Red Hot Chili Peppers",
    capo: 4,
    difficulty: 3,
    bpm: 85,
    timeSignature: "4/4",
    chordsUsed: ["G", "Am", "Em", "F", "C"],
    sections: [
      { name: "Verse", chords: ["G", "Am", "Em", "F"], strumPattern: "D . DU . D ." },
      { name: "Chorus", chords: ["C", "G", "F"], strumPattern: "D DU D DU" },
    ],
    tip: "Capo 4 gets you the simplified beginner-friendly chord shapes for this one.",
  },
  {
    title: "Hotel California",
    artist: "Eagles",
    capo: 0,
    difficulty: 4,
    bpm: 75,
    timeSignature: "4/4",
    chordsUsed: ["Am", "E", "G", "D", "F", "C", "Dm"],
    sections: [{ name: "Intro/Verse", chords: ["Am", "E", "G", "D", "F", "C", "Dm", "E"], strumPattern: "D DU D DU" }],
    tip: "The famous 8-chord descending progression — practice it slowly as a loop before adding the fingerstyle pattern.",
  },
  {
    title: "House of the Rising Sun",
    artist: "The Animals",
    capo: 0,
    difficulty: 3,
    bpm: 120,
    timeSignature: "6/8",
    chordsUsed: ["Am", "C", "D", "F", "E"],
    sections: [{ name: "Verse", chords: ["Am", "C", "D", "F", "Am", "E", "Am", "E"], strumPattern: "D DU DU DU" }],
    tip: "Traditionally fingerpicked as a rolling arpeggio across each chord rather than strummed.",
  },
  {
    title: "Fast Car",
    artist: "Tracy Chapman",
    capo: 2,
    difficulty: 3,
    bpm: 103,
    timeSignature: "4/4",
    chordsUsed: ["C", "G", "Em", "D"],
    sections: [{ name: "Verse", chords: ["C", "G", "Em", "D"], strumPattern: "D . DU . D ." }],
    tip: "Fingerpicked verses, strummed chorus — the capo 2 shapes stay the same the whole way through.",
  },
  {
    title: "Chasing Cars",
    artist: "Snow Patrol",
    capo: 2,
    difficulty: 1,
    bpm: 108,
    timeSignature: "4/4",
    chordsUsed: ["G", "D", "C"],
    sections: [{ name: "Verse/Chorus", chords: ["G", "D", "C"], strumPattern: "D . . . D . . ." }],
    tip: "Only three chords for the entire song — let each one ring out over a full bar.",
  },
  {
    title: "Budapest",
    artist: "George Ezra",
    capo: 4,
    difficulty: 2,
    bpm: 130,
    timeSignature: "4/4",
    chordsUsed: ["C", "F", "Am", "G"],
    sections: [{ name: "Verse/Chorus", chords: ["C", "F", "Am", "G"], strumPattern: "D DU UDU" }],
    tip: "Capo 4 gives you George Ezra's low, warm original key using simple open-chord shapes.",
  },
  {
    title: "Someone You Loved",
    artist: "Lewis Capaldi",
    capo: 1,
    difficulty: 2,
    bpm: 110,
    timeSignature: "4/4",
    chordsUsed: ["C", "G", "Am", "F"],
    sections: [{ name: "Verse/Chorus", chords: ["C", "G", "Am", "F"], strumPattern: "D . DU . D ." }],
    tip: "The same I-V-vi-IV loop as Iris and Someone Like You — recognize the pattern and you're most of the way there.",
  },
  {
    title: "Stay With Me",
    artist: "Sam Smith",
    capo: 0,
    difficulty: 2,
    bpm: 85,
    timeSignature: "4/4",
    chordsUsed: ["Am", "F", "C", "G"],
    sections: [{ name: "Verse/Chorus", chords: ["Am", "F", "C"], strumPattern: "D . . D . . ." }],
    tip: "A soulful, spacious ballad — resist the urge to strum too much and let space be part of the sound.",
  },
  {
    title: "More Than Words",
    artist: "Extreme",
    capo: 0,
    difficulty: 3,
    bpm: 72,
    timeSignature: "4/4",
    chordsUsed: ["G", "Cadd9", "Am7", "C", "D"],
    sections: [{ name: "Verse", chords: ["G", "Cadd9", "Am7", "C", "D"], strumPattern: "D . DU . D ." }],
    tip: "Almost entirely fingerpicked — a great next step once basic strumming feels solid.",
  },
  {
    title: "Photograph",
    artist: "Ed Sheeran",
    capo: 2,
    difficulty: 2,
    bpm: 78,
    timeSignature: "4/4",
    chordsUsed: ["D", "Bm", "A", "G"],
    sections: [{ name: "Verse/Chorus", chords: ["D", "Bm", "A", "G"], strumPattern: "D . DU . D ." }],
    tip: "The vi-IV-I-V family again, just reordered — a great song for recognizing progressions by ear.",
  },
  {
    title: "Tears in Heaven",
    artist: "Eric Clapton",
    capo: 2,
    difficulty: 3,
    bpm: 66,
    timeSignature: "4/4",
    chordsUsed: ["G", "D", "Em", "C"],
    sections: [{ name: "Verse", chords: ["G", "D", "Em", "C", "G", "D", "C"], strumPattern: "D . DU . D ." }],
    tip: "Fingerpicked and gentle — take the tempo slow and prioritize letting each chord ring clean.",
  },
  {
    title: "Wish You Were Here",
    artist: "Pink Floyd",
    capo: 0,
    difficulty: 3,
    bpm: 63,
    timeSignature: "4/4",
    chordsUsed: ["G", "Em7", "A7sus4", "D", "C"],
    sections: [
      { name: "Intro", chords: ["Em7", "G", "Em7", "A7sus4"], strumPattern: "D DU D DU" },
      { name: "Verse", chords: ["G", "D", "Em7", "G", "C", "D"], strumPattern: "D DU D DU" },
    ],
    tip: "That iconic intro riff is really just Em7 and A7sus4 — nail the riff first, then the chords underneath it.",
  },
  {
    title: "Dust in the Wind",
    artist: "Kansas",
    capo: 0,
    difficulty: 4,
    bpm: 78,
    timeSignature: "6/8",
    chordsUsed: ["C", "G", "Am", "Dm", "D"],
    sections: [
      { name: "Verse", chords: ["C", "G", "Am", "G"], strumPattern: "D DU DU DU" },
      { name: "Chorus", chords: ["D", "G", "Am"], strumPattern: "D DU DU DU" },
    ],
    tip: "A Travis-picking classic — practice the fingerpicking pattern on a single C chord before moving through changes.",
  },
  {
    title: "Landslide",
    artist: "Fleetwood Mac",
    capo: 3,
    difficulty: 3,
    bpm: 72,
    timeSignature: "4/4",
    chordsUsed: ["C", "G", "Am", "Em"],
    sections: [{ name: "Verse", chords: ["C", "G", "Am", "G"], strumPattern: "D . DU . D ." }],
    tip: "Capo 3 gives you the simplified open-chord shapes for Fleetwood Mac's original key.",
  },
  {
    title: "Take Me Home, Country Roads",
    artist: "John Denver",
    capo: 2,
    difficulty: 2,
    bpm: 92,
    timeSignature: "4/4",
    chordsUsed: ["G", "Em", "D", "C"],
    sections: [
      { name: "Verse", chords: ["G", "Em", "D", "C", "G", "D", "G"], strumPattern: "D DU UDU" },
      { name: "Chorus", chords: ["G", "D", "Em", "C", "G", "D", "G"], strumPattern: "D DU UDU" },
    ],
    tip: "A singalong classic on four open chords — great for practicing steady strumming while singing.",
  },
  {
    title: "Boulevard of Broken Dreams",
    artist: "Green Day",
    capo: 1,
    difficulty: 2,
    bpm: 84,
    timeSignature: "4/4",
    chordsUsed: ["Em", "G", "D", "A"],
    sections: [{ name: "Verse", chords: ["Em", "G", "D", "A"], strumPattern: "D . D . D ." }],
    tip: "Chord changes land roughly every two beats — slower than most Green Day songs, good for steady practice.",
  },
];

export function findPopularSong(query: string): PopularSong | undefined {
  const q = query.trim().toLowerCase();
  if (!q) return undefined;
  return POPULAR_SONGS.find((s) => s.title.toLowerCase() === q || `${s.title} ${s.artist}`.toLowerCase() === q);
}
